development:
  adapter: sqlite3
  database: db/trendz_development.sqlite
  pool: 5
  timeout: 5000
  username:
  password:

test:
  adapter: postgresql
  database: trendz_test
  timeout: 5000
  username: postgres
  password:

production:
  adapter: postgresql
  database: trendz
  timeout: 5000
  username: postgres
  password: 
